name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build containers using docker-compose
      run: docker-compose build
    - name: run pytest in docker-compose
      run: docker-compose -f docker-compose-test.yml up --exit-code-from stagedp
